services:
  spring-boot:
    build: .
    ports:
      - 8088:8088
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: 17052002
      MYSQL_PORT: 3306
      MYSQL_DATABASE: spring_azure_blob
      AZURE_ACCOUNT_NAME: didanjava
      AZURE_CONNECTION_STRING: DefaultEndpointsProtocol=https;AccountName=didanjava;AccountKey=sMRV7V7Am8gostA3S/ThN4oV1/4zXly26Q6zjm0UjKoKMqBtSIp329jACzfO/EEPI3Ulbwk1Ysal+ASt8PqdnQ==;EndpointSuffix=core.windows.net
    depends_on:
        - mysql
  mysql:
    container_name: mysqldb
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 17052002
      MYSQL_DATABASE: spring_azure_blob
    volumes:
      - ./mysql.sql:/docker-entrypoint-initdb.d/mysql.sql