azure:
  storage:
    endpoint: https://zdlab.blob.core.windows.net/
    connection:
      string: DefaultEndpointsProtocol=https;AccountName=zdlab;AccountKey=ALu/f/GeBTIUnwgCtzwL1erWrazsiJlckpzc0ChHOF0aBuHTyg41Htq/T4maDS0WUl4prBWFAK8X+AStwCTXyg==;EndpointSuffix=core.windows.net
    account:
      name: zdlab
    key: sMRV7V7Am8gostA3S/ThN4oV1/4zXly26Q6zjm0UjKoKMqBtSIp329jACzfO/EEPI3Ulbwk1Ysal+ASt8PqdnQ==

server:
  port: 8088

# Kết nối mySQL
# Docker và Localhost
spring:
  datasource:
    url: jdbc:mysql://mysqldb:localhost:3306/spring_azure_blob?serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 17052002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB


## JWT
jwt:
  secretkey: wyD7j04/rzm+8EABKgQTPO9cFojZI2Q2xRPycfhHtZc=

## Swagger v3
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    csrf:
      enabled: false
    path: /api-docs.html
    tags-sorter: alpha
    operations-sorter: alpha
  cache:
    disabled: true