azure:
  storage:
    endpoint: https://didanjava.blob.core.windows.net/
    connection:
      string: DefaultEndpointsProtocol=https;AccountName=didanjava;AccountKey=sMRV7V7Am8gostA3S/ThN4oV1/4zXly26Q6zjm0UjKoKMqBtSIp329jACzfO/EEPI3Ulbwk1Ysal+ASt8PqdnQ==;EndpointSuffix=core.windows.net
    account:
      name: didanjava
    key: sMRV7V7Am8gostA3S/ThN4oV1/4zXly26Q6zjm0UjKoKMqBtSIp329jACzfO/EEPI3Ulbwk1Ysal+ASt8PqdnQ==

server:
  port: 8088

# Kết nối mySQL
# Docker và Localhost
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/spring_azure_blob
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:17052002}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


## JWT
jwt:
  secretkey: wyD7j04/rzm+8EABKgQTPO9cFojZI2Q2xRPycfhHtZc=